### ISSUE TITLE
Slick not working as expected

### ISSUE THREAD

**Issue by ubergeoff** [ubergeoff/flingo#1]
**Describe the bug**

Slick not showing images...

**To Reproduce**

I tried and face a issue: https://i.gyazo.com/6559ab687bc8011f91ff15743b968360.mp4
Current I stopped debug that issue.

So I'm using the slick with jquery to push live my project.

I am expecting your final vanilla js version to use, @ubergeoff.

It would be great if you make a web page to explain the difference between your version with Kenwheeler (if have)

**Comment by ubergeoff** [comment]
Hi there @chinhphan099

There should be no difference between Kenwheeler's Slick and UberSlick - however - some small issues might pop-up as more people try to make use of it, in different scenarios...

Other than that: I believe lazy loading images - has not been completed... Are you making use of the "lazy load images" option..?

++

Is there some way you can share your code with me, or provide a small code snippet of what you are trying to achieve..?

**Comment by chinhphan099** [comment]
Hi @ubergeoff ,

I added one line at 636: https://i.gyazo.com/037139a3fb306df39d57f187666474e3.png
And it resolve my issue.

**Comment by ubergeoff** [comment]
OK @chinhphan099

Never came across this issue. Do you know what might have been required/missing..?

++ Do you feel I should I add this line in as well to the source..?

**Comment by chinhphan099** [comment]
Yes ! I think you should add that line to the source.

You can debug by add breakpoint at line 577 to check the value of _.$slides
And one breakpoint at line 636 (means after div.slick-list is created). The value of _.$slides is changed.

**Comment by chinhphan099** [comment]
This is my quick demo: https://chinhphan099.github.io/slick-vanilla/index.html @ubergeoff

**Comment by ubergeoff** [comment]
Please let me know if you are happy with change: 

++ please can you approve..? https://github.com/ubergeoff/flingo/pull/3/files

**Comment by chinhphan099** [comment]
It looks good to me @ubergeoff 

I applied: https://chinhphan099.github.io/slick-vanilla/index.html

Have nice weekend :)
