### ISSUE TITLE
Slicker: Styles for columns are on the wrong element

### ISSUE THREAD

**Issue by ThauEx** [ubergeoff/flingo#14]
**Describe the bug**
When using the options `slidesPerRow` the styles are on the wrong element.
Each row element has the number of slides in it, which are configured in `slidesPerRow`. In slicker the styles for the width are on the row instead of the slide.

**To Reproduce**
1. Create a slider with the option `slidesPerRow` and use an uneven number of slides
2. When using e.g. 2 for `slidesPerRow`, the first two are under each other instead if next.
3. Since we used an unevent amount of slides, the pre last row has an empty field and the last one has two elements

**Expected behavior**
Having a correct order and no gaps

**Additional context**
The issues is in those two lines:
https://github.com/ubergeoff/flingo/blob/master/libs/slicker/src/lib/slicker.ts#L677
https://github.com/ubergeoff/flingo/blob/master/libs/slicker/src/lib/slicker.ts#L682

Replace `row` with `originalSlides[target]` and it's working as intended. I compared the markup and with my suggested  change, it's like in the original slick.

**Comment by ubergeoff** [comment]
Yeah - so the original (Slick) code read like this:

```
_.$slider.children().children().children()
                .css({
                    'width':(100 / _.options.slidesPerRow) + '%',
                    'display': 'inline-block'
                });
```

Which was a kinda weird way to set styles - (you know running down the DOM tree like that)

So I might have missed something there... when converting...

Will relook at this - thank you...

**Comment by ThauEx** [comment]
Thanks for the change, can you please update the slicker package on npm? Thanks

**Comment by ubergeoff** [comment]
HI there 

Please see latest NPM package:

https://www.npmjs.com/package/@rooi/slicker

**Comment by ubergeoff** [comment]
Please see example here: https://www.flingo.co.za/slick/slick7

**Comment by ThauEx** [comment]
Thank you very much.
