### ISSUE TITLE
Slick Slider Breakpoints not working

### ISSUE THREAD

**Issue by asha23** [ubergeoff/flingo#20]
**Describe the bug**
Slick slider breakpoints don't seem to be working

**To Reproduce**
Add the following code

```
const slideConfig = {
			slidesToShow: numSlides,
			slidesToScroll: 1,
			autoplay: true,
			autoplaySpeed: 0,
			speed: scrollSpeed,
			dots: false,
			infinite: true,
			centerMode: false,
			variableWidth: false,
			pauseOnHover: false,
			cssEase: 'linear',
			draggable: false,
			swipe: false,
			responsive: [
				{
					breakpoint: 1200,
					settings: {
						slidesToShow: 8,
						slidesToScroll: 1,
					},
				},
				{
					breakpoint: 1008,
					settings: {
						slidesToShow: 6,
						slidesToScroll: 1,
					},
				},
				{
					breakpoint: 768,
					settings: {
						slidesToShow: 4,
						slidesToScroll: 1,
					},
				},
			],
		}

		slick = new Slicker(slickElement, slideConfig);
```

**Expected behavior**
Slider to change depending on breakpoint

**Screenshots**

**Desktop (please complete the following information):**
 - Chrome
 - Latest

**Additional context**
This is a great conversion and works really well. Just having these issues with breakpoints :)

**Comment by asha23** [comment]
Ah. Found the fix in pull requests...

**Comment by ubergeoff** [comment]
Hi there @asha23 - did the PR fix your breakpoint issue...? Should I merge the open PR..?
