### ISSUE TITLE
Responsive Slick not working

### ISSUE THREAD

**Issue by MendleM** [ubergeoff/flingo#21]
**Describe the bug**
I'm using EmberJS and `@rooi/slicker` for typing.

The responsive config for Slick isn't working. Everything else works a charm.

**To Reproduce**
```typescript
iimport { action } from "@ember/object";
import { Slicker } from "@rooi/slicker";
import Component from "@glimmer/component";

export default class HomePage extends Component {
  slick: Slicker;

  @action
  initializeCarousel(el: HTMLDivElement) {
    this.slick = new Slicker(el, {
      dots: true,
      infinite: true,
      speed: 300,
      slidesToShow: 3,
      autoplay: true,
      autoplaySpeed: 7000,
      responsive: [
        {
          breakpoint: 910,
          settings: {
            slidesToShow: 2,
            slidesToScroll: 1
          },
        },
      ],
    });
  }
}

```

**Expected behavior**
When I scale my window width down to 910px I'm expecting the carousel to show 2 tiles, instead of 3.

**Comment by MendleM** [comment]
I realise there is a PR up for this. Noting that the PR makes changes to the slick typescript file, and the `@rooi/slicker` includes just `.js` slick files. Not sure entirely how I can import the slick typescript mods from this repo into my existing project and then test those PR changes locally. Happy to be a guinea pig.

**Comment by ubergeoff** [comment]
Hi there - I will try make some time to look into the responsive issue...

However, if you would like to play around with some settings - you are more than welcome to pull the repo and try it out.

Over and above that if you would like to specifically just use the "slick" library "only" within your project - that should be possible as well.... would you like more details on that option..?

**Comment by ubergeoff** [comment]
++ new MR created: https://github.com/ubergeoff/flingo/pull/22/files

Would you like to test and review, before I merge..?

**Comment by ubergeoff** [comment]
Done

https://github.com/ubergeoff/flingo/pull/22
